# Generated by Django 4.2.2 on 2023-06-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_address', models.CharField(max_length=255)),
                ('student_age', models.IntegerField()),
                ('student_email', models.EmailField(max_length=254)),
                ('joining_date', models.DateField()),
                ('qualification', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('mobileno', models.CharField(max_length=255)),
            ],
        ),
    ]
